mindmap
  root((Portugal\n46 Clubes))
    Lisboa AML(9)
      Lisboa(4)
      Amadora(1)
      Oeiras(1)
      Cascais(1)
      Sintra(1)
      Loures(1)
    Porto AMP(8)
      Porto(3)
      Vila Nova de Gaia(2)
      Matosinhos(1)
      Gondomar(1)
      Maia(1)
    Setúbal(4)
    Braga(4)
    Aveiro(3)
    Coimbra(2)
    Faro Algarve(2)
    Leiria(2)
    Santarém(2)
    Viseu(1)
    Viana Castelo(1)
    Vila Real(1)
    Évora(1)
    Beja(1)
    Castelo Branco(1)
    Bragança(1)
    Guarda(1)
    Madeira(1)
    Açores(1)
