mindmap
  root((Portugal\n46 Clubes))
    Lisboa AML\n9 clubes
      Lisboa\n4
      Amadora\n1
      Oeiras\n1
      Cascais\n1
      Sintra\n1
      Loures\n1
    Porto AMP\n8 clubes
      Porto\n3
      VN Gaia\n2
      Matosinhos\n1
      Gondomar\n1
      Maia\n1
    Setúbal\n4 clubes
    Braga\n4 clubes
    Aveiro\n3 clubes
    Coimbra\n2 clubes
    Faro Algarve\n2 clubes
    Leiria\n2 clubes
    Viseu\n1-2 clubes
    Santarém\n2 clubes
    Viana do Castelo\n1 clube
    Vila Real\n1 clube
    Évora\n1 clube
    Beja\n1 clube
    Castelo Branco\n1 clube
    Bragança\n1 clube
    Portalegre\n0-1 clube
    Guarda\n1 clube
    Madeira\n1 clube
    Açores\n1 clube
